name: Cypress Tests

on: [push] # Roda o teste toda vez que você der um push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Se o seu comando de teste for diferente de 'npm test', 
          # você pode especificar aqui
          browser: chrome
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_user_name: ${{ secrets.USER_NAME }}
          CYPRESS_user_password: ${{ secrets.USER_PASSWORD }}
          